### ISSUE TITLE
ynam - version of chrome newer

### ISSUE THREAD

**Issue by BabblingBafoon** [snowskeleton/ynam#40]
I love this tool and have been using it successfully for months. It's been weeks since I ran it and now it is trowing a lot of errors... but near the end it shows:
```selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.110 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome```

My Chrome install is in fact 116 now. Does ynam code need to be updated or something? Sorry I'm so clueless.

**Comment by snowskeleton** [comment]
This is a problem with the upstream package mintapi as noted [here](https://github.com/mintapi/mintapi/pull/614). Necessary changes have been submitted, just waiting approval.

**Comment by snowskeleton** [comment]
This issue has been resolved and merged into main. Update your `mintapi` package with
```
pip install -U git+https://github.com/mintapi/mintapi@main
```

**Comment by BabblingBafoon** [comment]
Thanks for this. I was able to successfully update mintapi, but I am still getting the same error of chromedriver being too new. Did I miss a step?

**Comment by snowskeleton** [comment]
It should "just work" with the latest few versions of chrome (tested back to 114, iirc). Make sure you delete any previously downloaded chromedrivers, update chrome, and post the full stack trace here if it still fails.On Sep 3, 2023, at 16:22, BabblingBafoon ***@***.***> wrote:﻿
Thanks for this. I was able to successfully update mintapi, but I am still getting the same error of chromedriver being too new. Did I miss a step?

**Comment by BabblingBafoon** [comment]
Hmm... I tried deleting the chromedriver file that I could find. It was in the root of my user folder. Not sure if there is another location? Anyway, it didn't seem to do anything to replace it.

I'm sure I am missing something. I apologize for my lack of understanding on this. Should I uninstall Chrome completely and reinstall?
<img width="485" alt="image" src="https://github.com/snowskeleton/ynam/assets/99982983/d51c0c00-8ad3-4444-9688-3b1df3d96844">


Here is what spits out when I run `ynam`: (is this the "full stack trace" you mentioned?)

```
~ % ynam
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ynam/main.py", line 24, in main
    mint_transactions = mint_api.get_transactions(start_date=arg('days'))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ynam/mint_api.py", line 50, in get_transactions
    items = client.get_transaction_data()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mintapi/endpoints.py", line 647, in get_transaction_data
    data = self._get_transaction_data(json=payload.to_dict(), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mintapi/endpoints.py", line 315, in _get_transaction_data
    return self.post(
           ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mintapi/endpoints.py", line 37, in post
    return self.request(method="POST", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mintapi/rest.py", line 121, in request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://mint.intuit.com/pfm/v1/transactions/search

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/ynam", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ynam/main.py", line 26, in main
    mint_api.updateAuth()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ynam/mint_api.py", line 71, in updateAuth
    browser = self.browser(
              ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mintapi/browser.py", line 57, in __init__
    self.login_and_get_token(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mintapi/browser.py", line 113, in login_and_get_token
    self.driver = driver or _create_web_driver_at_mint_com(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mintapi/signIn.py", line 203, in _create_web_driver_at_mint_com
    return Chrome(options=chrome_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumrequests/request.py", line 148, in __init__
    super(RequestsSessionMixin, self).__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.140 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Stacktrace:
0   chromedriver                        0x0000000102c416b8 chromedriver + 4937400
1   chromedriver                        0x0000000102c38b73 chromedriver + 4901747
2   chromedriver                        0x00000001027f6616 chromedriver + 435734
3   chromedriver                        0x0000000102828d10 chromedriver + 642320
4   chromedriver                        0x000000010282418a chromedriver + 622986
5   chromedriver                        0x000000010282067c chromedriver + 607868
6   chromedriver                        0x0000000102867a08 chromedriver + 899592
7   chromedriver                        0x0000000102866ebf chromedriver + 896703
8   chromedriver                        0x000000010285dde3 chromedriver + 859619
9   chromedriver                        0x000000010282bd7f chromedriver + 654719
10  chromedriver                        0x000000010282d0de chromedriver + 659678
11  chromedriver                        0x0000000102bfd2ad chromedriver + 4657837
12  chromedriver                        0x0000000102c02130 chromedriver + 4677936
13  chromedriver                        0x0000000102c08def chromedriver + 4705775
14  chromedriver                        0x0000000102c0305a chromedriver + 4681818
15  chromedriver                        0x0000000102bd592c chromedriver + 4495660
16  chromedriver                        0x0000000102c20838 chromedriver + 4802616
17  chromedriver                        0x0000000102c209b7 chromedriver + 4802999
18  chromedriver                        0x0000000102c3199f chromedriver + 4872607
19  libsystem_pthread.dylib             0x00007ff81253b1d3 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff812536bd3 thread_start + 15
```
